### ISSUE TITLE
Update to 20w09a

### ISSUE THREAD

**Issue by Yuuki2012** [Ladysnake/Beem#3]
For 20w09a change:

```
# Fabric Properties
minecraft_version=20w06a
yarn_mappings=20w06a+build.6
loader_version=0.7.8+build.184

#Fabric api
fabric_version=0.4.30+build.294-1.16
```
to
```
# Fabric Properties
minecraft_version=20w09a
yarn_mappings=20w09a+build.2
loader_version=0.7.8+build.184

#Fabric api
fabric_version=0.4.33+build.301-1.16
```

And

```
MinecraftClient.getInstance().player.sendChatMessage(new TranslatableText("message.beem.toggled."+beem).formatted(Formatting.GOLD).asString());
```
to
```
MinecraftClient.getInstance().player.addMessage(new TranslatableText("message.beem.toggled."+beem).formatted(Formatting.GOLD), false);
```

Sorry I don't know how to PR.

**Comment by Pyrofab** [comment]
Thanks for the contribution !
If you have git on your computer, doing a PR requires you to click the `fork` button on github, clone the fork on your computer, do your changes, push and click the "open a pull request" button on your fork.
Otherwise, if you are sure your changes won't break anything, you can use the web interface to edit the files, it will suggest a PR by itself.

**Comment by Yuuki2012** [comment]
Okay thanks! :)
